### ISSUE TITLE
Versions 1.3.0 and 1.4.0 break Jest test runner

### ISSUE THREAD

**Issue by ljle** [backupfire/backupfire-firebase#70]
While updating our project's Firebase dependencies (including this package) running our unit tests suite (Jest) was failing (both locally and in CI) with this error:

![image](https://user-images.githubusercontent.com/696474/172449801-b06e469f-d392-485e-8170-3200d55dcae7.png)

I reverted everything and started to test every package and it turns out it's this one (you can see it at the end of the stack trace).

I tested both 1.3.0 and 1.4.0 and both error out, 1.2.0 however does not.

We're using Node 16.15.1 and `firebase-tools` 11.0.1

**Comment by kossnocorp** [comment]
**Thank you for reporting! I managed to reproduce the problem and hopefully will find a solution real soon.**

The root of the issue here is in `firebase-tools` dependency `marked-terminal` requiring `node:process`:

![image](https://user-images.githubusercontent.com/52201/172510963-7f042964-cd01-4a2e-b6d4-1533902b479c.png)

It is indeed a supported by Node.js v16:

![image](https://user-images.githubusercontent.com/52201/172511389-876e27b4-6318-4d47-8055-880341e0210f.png)

But still breaks when running with Jest:

![image](https://user-images.githubusercontent.com/52201/172514016-4b676509-81f2-4053-a851-fdda49852b97.png)

**Comment by kossnocorp** [comment]
The solution for you would be to upgrade Jest to the latest version. It seems that it incorrectly transpiles legit code. Could you please try upgrading it and running the code again?

I also reported a problem in `marked-terminal` that caused the error: https://github.com/mikaelbr/marked-terminal/pull/127

**Comment by ljle** [comment]
Thanks for the quick response @kossnocorp, I'll try that and get back to you on this. Also this is unrelated but while I was deploying some functions I noticed this warning, thought you should know.

![image](https://user-images.githubusercontent.com/696474/172685853-a8ace98f-3dc2-4174-89cc-30088a1fdb0f.png)

**Comment by ljle** [comment]
Closing as this no longer is an issue on version `1.8.1`.
